/*
    Generated by Atomist on 05 07 2016 
*/
package com.demo;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for Simpleaggregate.
* Don't even think of using XML.
*/
@Configuration
public class SimpleaggregateConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}